initial Japanese localization
northpolesec/santa pull request #177
Opened 2024-12-17 08:16 UTC by arubdesu

All strings as of late 2024 AFAICT, spot-checked by Koji Arita.
May have issue on "Prevent future notifications for this application for " because sentence doesn't end that way grammatically in Japanese, trusting that `\n\n`'s & `<br />`'s will be interpreted correctly.

2024-12-17 08:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/northpolesec/santa?pullRequest=177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/northpolesec/santa?pullRequest=177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/northpolesec/santa?pullRequest=177) it.</sub>

2024-12-17 14:44 UTC, russellhancox commented
![image](https://github.com/user-attachments/assets/bc6c2ba3-d865-40ca-8be7-2dc4e52b50ee)

![image](https://github.com/user-attachments/assets/cb3a9251-baf4-49b9-a810-e111a2b6773e)

2024-12-17 15:05 UTC, russellhancox commented
```----- Language ja -----
Missing: 4, ['Approve', 'Open...', 'authorize execution of ', 'authorize execution of the application ']
Extraneous: 0, []
Complete: 87.10%
```

3 of these missing strings are new and only apply to the new standalone mode but `Open...` is very important

2024-12-18 00:13 UTC, arubdesu commented
Pardon, this should match en.lproj's strings now.
Please note again that grammatically 'authorize execution _space_' strings wouldn't work to have the app name follow afterwards (with the space boundary) as spaces are omitted in Japanese text, this is another place where an inline variable would/should be used

2024-12-18 00:18 UTC, russellhancox commented
> Pardon, this should match en.lproj's strings now. Please note again that grammatically 'authorize execution _space_' strings wouldn't work to have the app name follow afterwards (with the space boundary) as e.g. the order of the phonetic word 'application' goes in the beginning/front of the sentence AND spaces are omitted in Japanese text, this is another place where an inline variable would/should be used

Interesting, I’ll have a look at updating the translations to include the app name tomorrow. Let’s get this in as-is for now and I’ll @ you when we can update to be more grammatically correct

2024-12-18 00:18 UTC, russellhancox requested changes

2024-12-18 00:18 UTC, russellhancox commented on Source/gui/Resources/ja.lproj/Localizable.strings
> +"The following application has been blocked from executing<br />because its trustworthiness cannot be determined" = "次のアプリケーションは信頼性を判断できないため、<br />実行がブロックされました
This string isn’t terminated

2024-12-18 01:43 UTC, arubdesu commented on Source/gui/Resources/ja.lproj/Localizable.strings
> +"The following application has been blocked from executing<br />because its trustworthiness cannot be determined" = "次のアプリケーションは信頼性を判断できないため、<br />実行がブロックされました
fixicated, pardon

2024-12-18 01:51 UTC, russellhancox approved these changes

2024-12-18 01:52 UTC, merged

2024-12-18 01:52 UTC, russellhancox commented
Thanks!

2024-12-18 02:39 UTC, arubdesu commented
Just to reiterate, I mentioned in the previous comment where variables either aren't currently used in English or other localizations or wouldn't be appended to the end of the sentence for Japanese, please take into account that:
```"Prevent future notifications for this application for " = "このアプリケーションからの通知を停止します```
should have the variable of the time period be between このアプリケーションからの通知をand 停止します
Also "authorize execution of the application " should instead be pre-pended, so it would be for example "Slackアプリケーションの実行を許可する"